/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.huypham.view;

/**
 *
 * @author duchu
 */
public class WeatherGui extends javax.swing.JFrame {

    /**
     * @return the lblIcon
     */
    public javax.swing.JLabel getLblIcon() {
        return lblIcon;
    }

    /**
     * Creates new form WeatherGui
     */
    public WeatherGui() {
        initComponents();
        this.setSize(this.getPreferredSize());
        // System.out.println("Preferred Width = " + this.getPreferredSize().width);
        // System.out.println("Preferred Height = " + this.getPreferredSize().height);
        // System.out.println("Width = " + this.getSize().width);
        // System.out.println("Width = " + this.getSize().height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnZip = new javax.swing.JPanel();
        lblZip = new javax.swing.JLabel();
        tfZip = new javax.swing.JTextField();
        btnSetLocation = new javax.swing.JButton();
        pnCity = new javax.swing.JPanel();
        lblCity = new javax.swing.JLabel();
        pnIconTemp = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        pnRefresh = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));

        pnZip.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnZip.setMinimumSize(new java.awt.Dimension(500, 40));
        pnZip.setPreferredSize(new java.awt.Dimension(500, 40));

        lblZip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZip.setText("Zip Code");
        pnZip.add(lblZip);

        tfZip.setColumns(15);
        tfZip.setActionCommand("<Not Set>");
        tfZip.setMinimumSize(new java.awt.Dimension(50, 22));
        pnZip.add(tfZip);

        btnSetLocation.setText("Set location");
        pnZip.add(btnSetLocation);

        getContentPane().add(pnZip, java.awt.BorderLayout.NORTH);

        pnCity.setBackground(new java.awt.Color(255, 255, 255));
        pnCity.setMinimumSize(new java.awt.Dimension(450, 125));
        pnCity.setPreferredSize(new java.awt.Dimension(450, 125));
        pnCity.setLayout(new java.awt.BorderLayout());

        lblCity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCity.setText("City");
        lblCity.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        lblCity.setMinimumSize(new java.awt.Dimension(450, 25));
        lblCity.setPreferredSize(new java.awt.Dimension(450, 25));
        pnCity.add(lblCity, java.awt.BorderLayout.NORTH);

        pnIconTemp.setBackground(new java.awt.Color(255, 255, 255));
        pnIconTemp.setMaximumSize(new java.awt.Dimension(2147483647, 80));
        pnIconTemp.setMinimumSize(new java.awt.Dimension(450, 80));
        pnIconTemp.setPreferredSize(new java.awt.Dimension(450, 80));
        pnIconTemp.setLayout(new javax.swing.BoxLayout(pnIconTemp, javax.swing.BoxLayout.Y_AXIS));

        lblIcon.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setText("Icon");
        lblIcon.setToolTipText("");
        lblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblIcon.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        lblIcon.setMinimumSize(new java.awt.Dimension(450, 100));
        lblIcon.setName(""); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(450, 100));
        pnIconTemp.add(lblIcon);

        lblTemp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTemp.setText("Temp");
        lblTemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTemp.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        lblTemp.setMinimumSize(new java.awt.Dimension(450, 32));
        lblTemp.setPreferredSize(new java.awt.Dimension(450, 32));
        pnIconTemp.add(lblTemp);

        pnCity.add(pnIconTemp, java.awt.BorderLayout.CENTER);

        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescription.setText("Description");
        lblDescription.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        lblDescription.setMinimumSize(new java.awt.Dimension(450, 20));
        lblDescription.setPreferredSize(new java.awt.Dimension(450, 20));
        pnCity.add(lblDescription, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnCity, java.awt.BorderLayout.CENTER);

        pnRefresh.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnRefresh.setMinimumSize(new java.awt.Dimension(450, 35));
        pnRefresh.setPreferredSize(new java.awt.Dimension(450, 35));

        btnRefresh.setText("Refresh");
        pnRefresh.add(btnRefresh);

        getContentPane().add(pnRefresh, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSetLocation;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblZip;
    private javax.swing.JPanel pnCity;
    private javax.swing.JPanel pnIconTemp;
    private javax.swing.JPanel pnRefresh;
    private javax.swing.JPanel pnZip;
    private javax.swing.JTextField tfZip;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnRefresh
     */
    public javax.swing.JButton getBtnRefresh() {
        return btnRefresh;
    }

    /**
     * @return the btnSetLocation
     */
    public javax.swing.JButton getBtnSetLocation() {
        return btnSetLocation;
    }

    /**
     * @return the lblCity
     */
    public javax.swing.JLabel getLblCity() {
        return lblCity;
    }

    /**
     * @return the lblDescription
     */
    public javax.swing.JLabel getLblDescription() {
        return lblDescription;
    }

    /**
     * @return the lblTemp
     */
    public javax.swing.JLabel getLblTemp() {
        return lblTemp;
    }

    /**
     * @return the tfZip
     */
    public javax.swing.JTextField getTfZip() {
        return tfZip;
    }
}
